# Generated by Django 5.1.4 on 2026-06-17 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vats.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Number')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('problem_descp', models.TextField(max_length=500, verbose_name='Problem Description')),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=50, null=True, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Scoping', 'Scoping'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], max_length=50, null=True, verbose_name='Status')),
                ('due_by', models.DateTimeField(blank=True, help_text='Auto-set from priority when ticket is assigned. Shows on dashboard.', null=True, verbose_name='SLA Due By')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Auto-set when status changes to Completed or Cancelled.', null=True, verbose_name='Resolved At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tasks', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vats.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Issues', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vats.subcategory')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Worknote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Create', 'Create'), ('Comment', 'Comment'), ('Field', 'Field')], max_length=50, null=True, verbose_name='Type')),
                ('comment', models.TextField(verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date/Time')),
                ('field_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Field name')),
                ('old_value', models.CharField(blank=True, max_length=40, null=True, verbose_name='Old value')),
                ('new_value', models.CharField(blank=True, max_length=40, null=True, verbose_name='new value')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worknotes', to='vats.ticket')),
            ],
            options={
                'verbose_name': 'Worknote',
                'verbose_name_plural': 'Worknotes',
            },
        ),
    ]
