# Generated by Django 5.1.4 on 2026-09-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="csat_feedback",
            field=models.TextField(
                blank=True,
                help_text="Optional free-text feedback submitted alongside the CSAT rating.",
                max_length=500,
                null=True,
                verbose_name="CSAT Feedback",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="csat_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                help_text="1-5 satisfaction rating, submitted by the ticket creator once the ticket is Completed.",
                null=True,
                verbose_name="CSAT Rating",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Auto-set the first time a Manager moves the ticket past 'Assigned' (Scoping/In Progress/Completed/Cancelled/Rejected).",
                null=True,
                verbose_name="First Response At",
            ),
        ),
    ]
